name: Firebase Deploy
on:
  push:
    branches:
      - main  # 코드를 업로드하는 브랜치 이름 (main 또는 master 확인 필요)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # GitHub Secrets에 등록된 값을 사용합니다.
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          
          # 배포될 채널 (live는 실제 운영 사이트)
          channelId: live
          
          # 프로젝트 ID를 hanroro-web으로 수정했습니다.
          projectId: "hanroro-web"
